version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/schoolyard
hooks:
  AfterInstall:
    - location: deploy-scripts/install.sh
      timeout: 600
      runas: ec2-user
  ApplicationStart:
    - location: deploy-scripts/start.sh
      timeout: 300
      runas: ec2-user